name: Integration tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: false  # Disable LFS

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements[test].txt

    - name: Run tests
      run: |
        python integration_tests.py

    - name: Coverage check
      run: |
        coverage xml -o coverage.xml
        coverage report --fail-under=80

    - name: Coverage badge
      if: github.event_name == 'push'  # Only run on push, not pull_request
      run: |
        COVERAGE_PERCENT=$(coverage report | grep 'TOTAL' | awk '{print $4}' | sed 's/%//')
        curl -o coverage-badge.svg https://img.shields.io/badge/Coverage-${COVERAGE_PERCENT}%25-brightgreen
        sed -i 's#!\[Coverage\](.*)#![Coverage](./coverage-badge.svg)#' README.md
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add coverage-badge.svg README.md
        git commit -m "Update coverage badge"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication
